In [1]:
import numpy as np

In [7]:
phase_shifts_r_fo_27 = np.loadtxt("artifacts/phase_shifts_r-fo-py2.7.18-seed49.csv", delimiter=',')
phase_shifts_r_fo_313 = np.loadtxt("artifacts/phase_shifts_r-fo-py3.13.12-seed49.csv", delimiter=',')

phase_shifts_r_fo_27 - phase_shifts_r_fo_313

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
phase_shifts_r_so_27 = np.loadtxt("artifacts/phase_shifts_r-so-py2.7.18-seed49.csv", delimiter=',')
phase_shifts_r_so_313 = np.loadtxt("artifacts/phase_shifts_r-so-py3.13.12-seed49.csv", delimiter=',')

phase_shifts_r_so_27 - phase_shifts_r_so_313

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [5]:
phase_shifts_d_fo_27 = np.loadtxt("artifacts/phase_shifts_d-fo-py2.7.18-seed49.csv", delimiter=',')
phase_shifts_d_fo_313 = np.loadtxt("artifacts/phase_shifts_d-fo-py3.13.12-seed49.csv", delimiter=',')

phase_shifts_d_fo_27 - phase_shifts_d_fo_313

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
phase_shifts_d_so_27 = np.loadtxt("artifacts/phase_shifts_d-so-py2.7.18-seed49.csv", delimiter=',')
phase_shifts_d_so_313 = np.loadtxt("artifacts/phase_shifts_d-so-py3.13.12-seed49.csv", delimiter=',')

phase_shifts_d_so_27 - phase_shifts_d_so_313

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])